"""empty message

Revision ID: a40839f4ae43
Revises: 
Create Date: 2020-09-20 17:16:25.125647

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a40839f4ae43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations',
                    'additional_info',
                    existing_type=sa.TEXT(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations',
                    'additional_info',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###
